### ISSUE TITLE
compile environment

### ISSUE THREAD

**Issue by smileAllYears** [huzi96/caffe-android-lib-distro#1]
i compile failed。it always prompt me:"readlink: illegal option -- f usage: readlink [-n] [file ...]" on mac os x
i use the command is "./build.sh /Users/zx/Library/Android/sdk/ndk-bundle"

**Comment by huzi96** [comment]
This is a problem caused by difference in the behavior of readlink in macOS. I suggest installing greadlink on macOS and configure using `alias readlink=greadlink;./build.sh`. Also there is a minor update of the building script, please pull and update.
